# ========== Hazop Formula ============
# Settings and configuration arguments.
[package]
name = "toml"
description = ""
help = ""
version = "0.4.2"
author = "Dmytro Kostiuk <X100@X100.LINK>"

[common]
data_dir = "./data"
data_ext = ".xlsx"
text_dir = "./txt"

[hazop]
pattern = "^[a-zA-Z0-9.]*-(?i)(metadata|analysis)$"
elements = [
	{ name = "Label", regex = "(?i)(name|label|parameter)", type = "string", min = 0, max = 40 },
	{ name = "Description", regex = "(?i)(description)", type = "string", min = 0, max = 160 },
	{ name = "Reference", regex = "(?i)(^ref.?|^no.?)", type = "integer", min = 0, max = 1000 },
	{ name = "Guide Word", regex = "(?i)(guide\\s?word)", type = "string", min = 0, max = 40 },
	{ name = "Parameter", regex = "(?i)(parameter)", type = "string", min = 0, max = 40 },
	{ name = "Deviation", regex = "(?i)(deviation)", type = "string", min = 0, max = 80 },
	{ name = "Cause", regex = "(?i)(cause)", type = "string", min = 0, max = 160 },
	{ name = "Consequense", regex = "(?i)(consequense|effect)", type = "string", min = 0, max = 160 },
	{ name = "Safeguard", regex = "(?i)(safeguard|protect(ion|ive)|systems?)", type = "string", min = 0, max = 160 },
	{ name = "Action Ref.", regex = "(?i)(action|recommendation)\\s?(ref.?|no.?)$", type = "integer", min = 0, max = 1000 },
	{ name = "Action", regex = "(?i)(action|recommendation)$", type = "string", min = 0, max = 160 },
	{ name = "Action On", regex = "(?i)(action|recommendation)\\s?on.?$", type = "string", min = 0, max = 40 },
	{ name = "Severity", regex = "(?i)(severity)", type = "integer", min = 0, max = 100 },
	{ name = "Likehood", regex = "(?i)(likehood|probability)", type = "integer", min = 0, max = 100 },
	{ name = "Risk Priotrity", regex = "(?i)(risk|priority)", type = "string", min = 0, max = 40 },
]
