# ========== Hazop Formula Settings ============
[program]
name = "Hazop study: tabular evaluation"
description = ""
help = ""
version = "1.1.1"
author = "Dmytro Kostiuk <X100@X100.LINK>"

[common]
data_dir = "data"
data_ext = ".xlsx"
report_dir = "report"
report_ext = ".txt"
temp_file = "template_file.txt"
temp_stdout = "template_stdout.txt"

[hazop]
data_type = { metadata = 0, analysis = 1 }
cell_type = { string = 0, integer = 1, float = 2 }
element = [
    { data_type = 0, name = "Label", regex = "^(?i)(name|label|parameter)", cell_type = 0, min_len = 0, max_len = 40 },
    { data_type = 0, name = "Description", regex = "^(?i)(description)", cell_type = 0, min_len = 0, max_len = 160 },
    { data_type = 1, name = "Reference", regex = "^(?i)(^ref.?|^no.?)", cell_type = 1, min_len = 0, max_len = 320 },
    { data_type = 1, name = "Guide Word", regex = "^(?i)(guide\\s?word)", cell_type = 0, min_len = 0, max_len = 40 },
    { data_type = 1, name = "Parameter", regex = "^(?i)(parameter)", cell_type = 0, min_len = 0, max_len = 40 },
    { data_type = 1, name = "Deviation", regex = "^(?i)(deviation)", cell_type = 0, min_len = 0, max_len = 80 },
    { data_type = 1, name = "Cause", regex = "^(?i)(cause)", cell_type = 0, min_len = 0, max_len = 160 },
    { data_type = 1, name = "Consequence", regex = "^(?i)(consequence|effect)", cell_type = 0, min_len = 0, max_len = 160 },
    { data_type = 1, name = "Safeguard", regex = "^(?i)(safeguard|protect(ion|ive)|systems?)", cell_type = 0, min_len = 0, max_len = 160 },
    { data_type = 1, name = "Action Ref.", regex = "^(?i)(action|recommendation)\\s?(ref.?|no.?)$", cell_type = 1, min_len = 0, max_len = 1000 },
    { data_type = 1, name = "Action", regex = "^(?i)(action|recommendation)$", cell_type = 0, min_len = 0, max_len = 160 },
    { data_type = 1, name = "Action On", regex = "^(?i)(action|recommendation)\\s?on.?$", cell_type = 0, min_len = 0, max_len = 40 },
    { data_type = 1, name = "Severity", regex = "^(?i)(severity)", cell_type = 1, min_len = 0, max_len = 100 },
    { data_type = 1, name = "Likehood", regex = "^(?i)(likehood|probability)", cell_type = 1, min_len = 0, max_len = 100 },
    { data_type = 1, name = "Risk Priority", regex = "^(?i)(risk\\s?priority)", cell_type = 0, min_len = 0, max_len = 40 },
]
